Mastering the IDE tasks
jetbrains-academy/rustlings-course pull request #103
Opened 2021-05-17 13:53 UTC by medvector

https://youtrack.jetbrains.com/issue/EDC-392

2021-05-20 14:45 UTC, medvector commented
Applied all the comments from @stephen-hero

2021-05-21 08:18 UTC, Geravant requested changes

2021-05-21 08:18 UTC, Geravant commented on Common Programming Concepts/Data Types/Understanding Types/task.md
> +Let's examine the code from the [Slices](course://Common Programming Concepts/Data Types/Slices) task more closely.
The Slices task [was moved](https://github.com/jetbrains-academy/rustlings-course/commit/e64b1b16b2e19e2ca865550c911a05d8fd8ac850) further in the curriculum, into the Understanding Ownership - Move Semantics lesson. I suggest removing the link and not referring to a parent at this point.

2021-05-21 08:18 UTC, Geravant commented on Common Programming Concepts/Functions/Extract Method Refactoring/src/main.rs
> +    let year2020 = 2020;
I understand, this is just an abstract example, and we probably will not change this over the years, but as we release it in 2021, maybe we should switch to year2021 = 2021?

2021-05-21 08:18 UTC, Geravant commented on Common Programming Concepts/Functions/Extract Method Refactoring/task.md
> +and then either press &shortcut:ExtractMethod; or choose *Refactor&rarr;Extract Method...* from the right-click menu.
Unfortunately, the \&rarr; is not rendered correctly on WIn10/ 2021.5-2021.1-637 plugin, it is rendered as a "?"
Maybe we can switch to -> for the time being? I'll create an issue about rendering in the YT

2021-05-21 08:18 UTC, Geravant commented on Common Programming Concepts/Variables/Introduce Variable Refactoring/task.md
> +*Note*: you can also use &shortcut:IntroduceConstant; or *Refactor&rarr;Introduce Constant...* from the right-click menu
Unfortunately, the &rarr; is not rendered correctly on WIn10/ 2021.5-2021.1-637 plugin, it is rendered as a "?"
Maybe we can switch to -> for the time being? I'll create an issue about rendering in the YT

2021-05-24 11:36 UTC, medvector commented
Fixed all the comments by @Geravant 
Please resolve comments.

2021-05-24 12:11 UTC, stephen-hero commented on Common Programming Concepts/If/Managing Conditions/task.md
> +Can you quickly understand what the code from `main.rs` file prints?
Can you quickly understand what the code from the `main.rs` file prints?

2021-05-24 12:11 UTC, stephen-hero commented on Common Programming Concepts/If/Managing Conditions/task.md
> +Now, can you quickly understand what the code from `main.rs` file prints?
Now, can you quickly understand what the code from the `main.rs` file prints?

2021-05-29 12:10 UTC, medvector commented
Applied the latest comments.

2021-06-01 09:44 UTC, Geravant approved these changes

2021-06-01 09:45 UTC, merged