Split manual for RustRover and IDEA in Getting Started/External Linter
jetbrains-academy/rustlings-course pull request #302
Opened 2024-10-18 11:13 UTC by kochaika

Based on the suggestion from https://github.com/jetbrains-academy/rustlings-course/pull/300

2024-10-18 13:50 UTC, stephen-hero requested changes

2024-10-18 13:50 UTC, stephen-hero commented on Introduction/Getting started/External Linter/task.md
> +IntelliJ Rust plugin doesn't detect all the errors. It relies on the Rust compiler to do that. While you are learning Rust, it is useful to see errors as you type. To have this behavior, we recommend
The IntelliJ Rust plugin doesn't detect all errors on its own; it relies on the Rust compiler for that. While learning Rust, it is helpful to see errors as you type. To achieve this, we recommend enabling an external linter as follows.

2024-10-18 13:50 UTC, stephen-hero commented on Introduction/Getting started/External Linter/task.md
> +Once you do that, %IDE_NAME% will report all the errors IntelliJ Rust plugin or Rust compiler detect.
Once you do that, %IDE_NAME% will report all errors detected by either the IntelliJ Rust plugin or the Rust compiler.

2024-10-18 13:50 UTC, stephen-hero commented on Introduction/Getting started/External Linter/task.md
> +Depending on the IDE you are using, the flow may be slightly different.
The steps may vary slightly depending on the IDE you're using.

2024-10-18 13:50 UTC, stephen-hero commented on Introduction/Getting started/External Linter/task.md
> +   - Check the **Run external linter on the fly** checkbox.
Check the **Run external linter on the fly** box.

2024-10-18 13:50 UTC, stephen-hero commented on Introduction/Getting started/External Linter/task.md
> +   - Check the **Run external linter on the fly** checkbox.
Check the **Run external linter on the fly** box.

2024-10-18 14:22 UTC, stephen-hero approved these changes

2024-10-21 15:29 UTC, Geravant approved these changes

2024-10-22 09:49 UTC, merged