Variables and functions test update
jetbrains-academy/rustlings-course pull request #44
Opened 2021-02-04 14:20 UTC by sofiiako

Updated the task (changed the solution, edited placeholder)

2021-02-05 11:48 UTC, Geravant requested changes
It is all good!
Would we move the if lesson before this as well?
We can also rename it into smth like "Veriables, functions and if test", though it might be a bit long

2021-02-06 22:51 UTC, sofiiako commented
@Geravant requested changes here: https://github.com/jetbrains-academy/rustlings-course/commit/26802f207186d5f341e8b9020cefe4262f0b594b

2021-02-09 11:07 UTC, Geravant requested changes

2021-02-09 11:07 UTC, Geravant commented on Common Programming Concepts/section-info.yaml
>  - If
Should we move the if lesson before the "Variables, Function and If test"?

2021-02-09 11:07 UTC, Geravant commented on Common Programming Concepts/section-info.yaml
> +- "Variables, Functions and If Test"
Does this attach the lesson correctly? I get an error with the quotes, but it seems to work fine without them/

2021-02-09 11:18 UTC, Geravant approved these changes

2021-02-09 11:18 UTC, merged