Sofia/getting started
jetbrains-academy/rustlings-course pull request #48
Opened 2021-02-10 14:13 UTC by sofiiako

2021-02-11 13:08 UTC, Geravant requested changes

2021-02-11 13:08 UTC, Geravant commented on Introduction/Getting started/Installation/task.md
>  You need to set up the environment in a system below are few things which you should check before the work.
I believe the default case would be to install the rust, so I suggest changing the "check before the work" to "do before the work" and move this sentence to the very top (before the "Unix" header)

2021-02-11 13:08 UTC, Geravant commented on Introduction/Getting started/Installation/task.md
>  ### Verification of Rust installation
This header now seems a bit out of place/ Maybe we can just drop it?

2021-02-11 14:24 UTC, sofiiako commented
@Geravant Added the requested minor changes in Installation: [29175bb](https://github.com/jetbrains-academy/rustlings-course/pull/48/commits/29175bb72d67806b4f301300781f6c783e6e6414)

2021-02-12 08:37 UTC, Geravant approved these changes

2021-02-12 08:39 UTC, Geravant approved these changes

2021-02-14 21:14 UTC, stephen-hero commented on Understanding Ownership/Move Semantics/Mutable Argument/task.md
>    The difference between this one and the previous ones is that the first line of `fn fill_vec` that had `let mut vec = vec;` is no longer there.
Unlike the previous cases, the first line of `fn fill_vec`, which had `let mut vec = vec;`, is now gone.

2021-02-14 21:32 UTC, sofiiako commented on Introduction/Getting started/Installation/task.md
> +4. Setup Rust toolchain (press "Setup toolchain" in the pop-up "No Rust toolchain configured").
"Setup" is the way it's spelled in IDEA
![toolchain](https://user-images.githubusercontent.com/5954159/107889651-3181df00-6f25-11eb-9b15-c8f5b2890232.png)

2021-02-14 21:38 UTC, sofiiako commented on Understanding Ownership/Move Semantics/Mutable Argument/task.md
> +Make me compile without adding new lines — just changing existing lines! (no lines with multiple semicolons necessary!)
"Make me compile" is the standard wording for these tasks in the original course, it's used everywhere... Not sure we should change it.

2021-02-14 21:39 UTC, sofiiako commented on Introduction/Getting started/Installation/task.md
> +4. Setup Rust toolchain (press "Setup toolchain" in the pop-up "No Rust toolchain configured").
same as line 26

2021-02-14 21:47 UTC, stephen-hero commented on Understanding Ownership/Move Semantics/Mutable Argument/task.md
> +Make me compile without adding new lines — just changing existing lines! (no lines with multiple semicolons necessary!)
I see.. Thought a lot about it, but without a context it's difficult to see all the connotations.. "Make me" sounds kinda weird, though, like - "Заставьте меня!" :)

2021-02-14 21:53 UTC, stephen-hero commented on Introduction/Getting started/Installation/task.md
> +4. Setup Rust toolchain (press "Setup toolchain" in the pop-up "No Rust toolchain configured").
Yes, these two are often confused, even by interface writers, I guess. However, 'setup' is a noun, while 'set up' is a verb. What I would suggest here then is a compromise: Set up Rust toolchain (press "Setup toolchain" in the pop-up "No Rust toolchain configured").

2021-02-15 10:45 UTC, sofiiako commented on Introduction/Getting started/Installation/task.md
> +4. Setup Rust toolchain (press "Setup toolchain" in the pop-up "No Rust toolchain configured").
Agreed)

2021-02-15 10:46 UTC, sofiiako commented on Understanding Ownership/Move Semantics/Mutable Argument/task.md
> +Make me compile without adding new lines — just changing existing lines! (no lines with multiple semicolons necessary!)
This is exactly the meaning I though was actually intended...))

2021-02-16 05:52 UTC, stephen-hero commented on Understanding Ownership/Move Semantics/Mutable Argument/task.md
> +Make me compile without adding new lines — just changing existing lines! (no lines with multiple semicolons necessary!)
Somewhat masochistic, but - whatever ))

2021-02-25 11:51 UTC, merged