Sofia/common collections/strings
jetbrains-academy/rustlings-course pull request #50
Opened 2021-02-26 16:09 UTC by sofiiako

2021-03-03 09:45 UTC, Geravant requested changes

2021-03-03 09:45 UTC, Geravant commented on Common Collections/Strings/HashMaps/task.md
> +    *count += 1;
I believe the tabulation is missing here for the *count +=1; line

2021-03-03 09:45 UTC, Geravant commented on Common Collections/Strings/Declaring a Vector/tests/tests.rs
> +//fn is_correct() {
We can remove this, as we are not using it after all

2021-03-03 09:45 UTC, Geravant commented on Common Collections/Strings/Loop Over a Vector/task-info.yaml
> +    placeholder_text: Fill this up so that each element in the Vec `v` is multiplied
Let's add //at the beginning of the placeholder text, so it won't be painted red by the Idea at the beginning of the exercise

2021-03-03 09:45 UTC, Geravant commented on Common Collections/Strings/Declaring a Vector/task-info.yaml
> +    placeholder_text: Declare your vector here
Let's add //at the beginning of the placeholder text, so it won't be painted red by the Idea at the beginning of the exercise

2021-03-03 09:45 UTC, Geravant commented on Common Collections/Strings/Declaring a HashMap/task-info.yaml
> +    placeholder_text: Declare your hash map here
Let's add //at the beginning of the placeholder text, so it won't be painted red by the Idea at the beginning of the exercise

2021-03-03 09:45 UTC, Geravant commented on Common Collections/Strings/Declaring a HashMap/task-info.yaml
> +    placeholder_text: Put more fruits in your basket here!
Let's add //at the beginning of the placeholder text, so it won't be painted red by the Idea at the beginning of the exercise

2021-03-03 09:45 UTC, Geravant commented on Common Collections/Strings/Declaring a HashMap/task.md
> +  the type for the `basket`.</div></li>
The tag does not work here, we should probably change the `` to an HTML tag

2021-03-03 09:45 UTC, Geravant commented on Common Collections/Strings/Modifying a HashMap/src/main.rs
> +    println!("Basket: {:?}", b);
We probably should modify it, it does not currently print anything, so it is unclear what modifications were made by the student

2021-03-03 09:45 UTC, Geravant commented
Great job!
The exercises seem very cool, just a few tweaks, mostly formatting stuff.

2021-03-03 16:53 UTC, sofiiako commented
@Geravant addressed the issues

2021-03-04 09:26 UTC, Geravant approved these changes

2021-03-04 09:26 UTC, merged