Sofia/enums
jetbrains-academy/rustlings-course pull request #52
Opened 2021-03-03 16:09 UTC by sofiiako

2021-03-05 09:15 UTC, Geravant requested changes

2021-03-05 09:15 UTC, Geravant commented on Enums/Enums and Pattern Matching/Intro/task.md
> +# Enums and Pattern Matching
The task-info.yaml is missing for this task

2021-03-05 09:15 UTC, Geravant commented on Enums/Enums and Pattern Matching/Implement Match/src/lib.rs
> +pub enum Message {
Should we add a main to demonstrate the results in this task?

2021-03-05 10:47 UTC, sofiiako commented
@Geravant Addressed the issues, see the commits above :)

2021-03-05 12:02 UTC, Geravant approved these changes

2021-03-05 12:02 UTC, merged

2021-03-23 10:13 UTC, stephen-hero commented on Enums/Enums and Pattern Matching/The Match Operator/task.md
> +Does `Some(5)` match `Some(i)`? Why yes it does! We have the same variant. The
Why, yes it does!

2021-03-23 10:13 UTC, stephen-hero commented on Enums/Enums and Pattern Matching/The Match Operator/task.md
> +The `_` pattern will match any value. By putting it after our other arms, the
When put after our other arms, the